version: 2

before:
  hooks:
    - go mod tidy

release:
  replace_existing_artifacts: true

builds:
  - main: ./cmd/iperf3_exporter
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/prometheus/common/version.Version={{.Version}}
      - -X github.com/prometheus/common/version.Branch={{.Branch}}
      - -X github.com/prometheus/common/version.Revision={{.ShortCommit}}
      - -X github.com/prometheus/common/version.BuildDate={{.Date}}
      - -X github.com/prometheus/common/version.BuildUser=goreleaser
    flags:
      - -trimpath

archives:
  - name_template: "{{ .ProjectName }}-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    files:
      - LICENSE
      - NOTICE
      - README.md

changelog:
  sort: asc
  use: github
  groups:
    - title: Features
      regexp: '^.*?feat(\(.+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?(fix|refactor)(\(.+\))??!?:.+$'
      order: 1
    - title: Documentation
      regexp: '^.*?docs(\(.+\))??!?:.+$'
      order: 2
    - title: Other
      order: 999
  filters:
    exclude:
      - '^test:'
      - '^chore:'
      - 'Merge pull request'
      - 'Merge branch'
